version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: khalifa
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: KKS
    ports:
      - "5431:5432"
    volumes:
      # Persist database files
      - postgres_data:/var/lib/postgresql/data
      # Mount the initialization script to run on first startup
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
